### ISSUE TITLE
Couple of errors in docs and makefile

### ISSUE THREAD

**Issue by Kirtai** [PDP-10/tops20-build#5]
The Makefile has a typo 
```
@@ -32,7 +32,7 @@ dec-7.0-tapes: tapes/dec
                bunzip2 tapes/dec/$${tapefunction}.tap.bz2 ;\
        done
 
-tapes/dev/install.tap: dec-7.0-tapes
+tapes/dec/install.tap: dec-7.0-tapes
```

The readme says to use 
```
make phase0/stamp
```
to build phase 0, however
```
make phase0/phase0.tap
```
seems to be the command needed to build it.

**Comment by larsbrinkhoff** [comment]
Thank you.  This repository is no longer maintained.  Would you like to add your fixes?

**Comment by Kirtai** [comment]
Oh, has it been moved, abandoned or is this one just "done"?

**Comment by larsbrinkhoff** [comment]
I'm sorry to say @kcr has passed away.

**Comment by Kirtai** [comment]
Oh, I'm sorry to hear that :(
I'll submit the fixes.

**Comment by Kirtai** [comment]
Fixes applied.

**Comment by larsbrinkhoff** [comment]
Thank you.  Feel free to contribute as much as you like!
